# This is workflow name
name: Hello

# Run on trigger
on:
  push:
    branches: [mail]

# Jobs section
jobs:
  greet:
    # GitHub runner
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "Hello Dosto"

      - name: Say hello to users
        run: echo "Hello $USER"
