name: self-hosted (Self Hosted)

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted   #  LOCAL MACHINE RUNNER

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker Hub using TOKEN
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/github-actions-app:latest .

      # Push to Docker Hub
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/github-actions-app:latest

      # Deploy on Local Machine
      - name: Run Container
        run: |
          docker compose down || true
          docker compose up -d --build --force-recreate
